<?php
/**
 * Canonical closure for non-public QA environments.
 *
 * Staging2 remains noindex, but approved public routes expose the URL that will
 * be canonical in Production. Protected working-name routes stay without a
 * canonical because they must not imply a publishable production counterpart.
 *
 * @package nuvanx-medical
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/** Whether the current strategy route is still under medical/legal review. */
function nvx_staging2_canonical_is_protected_review(): bool {
	if ( ! function_exists( 'nvx_strategy_current_page_key' ) || ! function_exists( 'nvx_strategy_page_catalog' ) ) {
		return false;
	}

	$key     = nvx_strategy_current_page_key();
	$catalog = nvx_strategy_page_catalog();

	return null !== $key
		&& isset( $catalog[ $key ]['review_status'] )
		&& 'approved_for_publication' !== $catalog[ $key ]['review_status'];
}

/** Build the public production URL for the current approved route. */
function nvx_staging2_public_canonical_url(): string {
	if ( nvx_staging2_canonical_is_protected_review() || is_404() || is_search() || is_preview() ) {
		return '';
	}

	if ( ! is_front_page() && ! is_home() && ! is_singular() ) {
		return '';
	}

	$path = function_exists( 'nvx_seo_current_path' )
		? nvx_seo_current_path()
		: (string) wp_parse_url( isset( $_SERVER['REQUEST_URI'] ) ? (string) $_SERVER['REQUEST_URI'] : '/', PHP_URL_PATH );

	$path = '/' . trim( (string) $path, '/' );
	if ( '/' !== $path ) {
		$path .= '/';
	}

	return 'https://nuvanx.com' . $path;
}

/**
 * Return a production canonical on Staging2 while preserving Production logic.
 *
 * @param mixed $url Canonical generated by Yoast.
 * @return mixed
 */
function nvx_staging2_filter_public_canonical( $url ) {
	if ( ! function_exists( 'nvx_seo_is_nonproduction_environment' ) || ! nvx_seo_is_nonproduction_environment() ) {
		return $url;
	}

	return nvx_staging2_public_canonical_url();
}
add_filter( 'wpseo_canonical', 'nvx_staging2_filter_public_canonical', 1000 );
add_filter( 'wpseo_opengraph_url', 'nvx_staging2_filter_public_canonical', 1000 );
