name: Block B Readiness Once

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/block-b-readiness-once.yml

permissions:
  contents: read
  actions: read

jobs:
  block_b:
    uses: ./.github/workflows/deploy.yml
    with:
      sha: 4775310be2b7dcdda18f8fd6de8e40041c2eb555
    secrets: inherit
