name: Staging2 Candidate Once

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/staging2-candidate-once.yml

permissions:
  contents: read

jobs:
  deploy_candidate:
    uses: ./.github/workflows/deploy-staging2.yml
    with:
      sha: 3a865f3710971fff3c7098df06edf58b630f8ef8
      run_block_c_acceptance: true
    secrets: inherit
