name: Staging2 Candidate Once

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/staging2-candidate-once.yml

permissions:
  contents: read

jobs:
  deploy_candidate:
    uses: ./.github/workflows/deploy-staging2.yml
    with:
      sha: ef5edb4bd4ea23e86b8123ab83e05e2f401229bc
      run_block_c_acceptance: true
    secrets: inherit
